module.exports = {
  Navigation: {},
  Pagination: {},
  Autoplay: {},
  EffectFade: {},
  EffectCube: {},
  EffectCoverflow: {},
  Thumbs: {},
  FreeMode: {},
  Grid: {},
  Manipulation: {},
  Zoom: {},
  Controller: {},
  A11y: {},
  History: {},
  HashNavigation: {},
  Keyboard: {},
  Mousewheel: {},
  Parallax: {},
  Scrollbar: {},
  Virtual: {},
};
